// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlXOx_bUC4zudjZpoD23XwiKciomLsCmI',
    appId: '1:945777090973:web:00bae64a8a575eb9974f74',
    messagingSenderId: '945777090973',
    projectId: 'mynotes-myflutter',
    authDomain: 'mynotes-myflutter.firebaseapp.com',
    storageBucket: 'mynotes-myflutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgn4yUKlkLrvp8luKLz9fpCMlspyS2Zuo',
    appId: '1:945777090973:android:5b00b70576afce04974f74',
    messagingSenderId: '945777090973',
    projectId: 'mynotes-myflutter',
    storageBucket: 'mynotes-myflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVtlVHUa1OYF8VL70up9KwNq-aqNedtdc',
    appId: '1:945777090973:ios:3426857d8ad3807b974f74',
    messagingSenderId: '945777090973',
    projectId: 'mynotes-myflutter',
    storageBucket: 'mynotes-myflutter.appspot.com',
    iosClientId:
        '945777090973-5nkk1knarugo0ieii0co9vp6092g0ae8.apps.googleusercontent.com',
    iosBundleId: 'com.360notes.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVtlVHUa1OYF8VL70up9KwNq-aqNedtdc',
    appId: '1:945777090973:ios:26aab860d910831f974f74',
    messagingSenderId: '945777090973',
    projectId: 'mynotes-myflutter',
    storageBucket: 'mynotes-myflutter.appspot.com',
    iosClientId:
        '945777090973-s6qaib9kj59khfd9b2d0dcvdu4l56bpu.apps.googleusercontent.com',
    iosBundleId: 'com.360notes.mynotes.RunnerTests',
  );
}
